name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 47.108.91.151 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -v chunfengfusu1@47.108.91.151 "
            set -e
            cd /var/www/me.github.io &&
            git stash save --keep-index || true &&
            git pull origin master &&
            git stash pop || true &&
            bundle install &&
            bundle exec jekyll build &&
            sudo chmod -R 755 /var/www/html/ &&
            sudo chown -R chunfengfusu1:chunfengfusu1 /var/www/html/ &&
            cp -r _site/* /var/www/html/
          "
